name: olist
version: "1.0.0"
profile: olist

model-paths:
  - models

models:
  olist:
    staging:
      +materialized: view
      +schema: staging

    intermediate:
      +materialized: ephemeral

    analytics:
      +materialized: table
      +schema: analytics