CREATE SCHEMA IF NOT EXISTS raw;
CREATE SCHEMA IF NOT EXISTS staging;
CREATE SCHEMA IF NOT EXISTS analytics;

GRANT ALL PRIVILEGES ON SCHEMA raw TO olist_user;
GRANT ALL PRIVILEGES ON SCHEMA staging TO olist_user;
GRANT ALL PRIVILEGES ON SCHEMA analytics TO olist_user;