name: olist
version: "1.0.0"
profile: olist

model-paths:
  - models

models:
  olist:
    staging:
      +database: staging
      +materialized: view

    intermediate:
      +materialized: ephemeral
    
    analytics:
      +database: analytics
      +materialized: table