olist:
  target: dev

  outputs:
    dev:
      type: mysql
      server: localhost
      port: 3306
      database: raw
      schema: raw
      user: warehouse
      password: "{{ env_var('MYSQL_PASSWORD') }}"
      threads: 4