
CREATE DATABASE IF NOT EXISTS raw;
CREATE DATABASE IF NOT EXISTS staging;
CREATE DATABASE IF NOT EXISTS analytics;

GRANT ALL PRIVILEGES ON raw.* TO 'warehouse'@'%';
GRANT ALL PRIVILEGES ON staging.* TO 'warehouse'@'%';
GRANT ALL PRIVILEGES ON analytics.* TO 'warehouse'@'%';
GRANT ALL PRIVILEGES ON warehouse.* TO 'warehouse'@'%';

FLUSH PRIVILEGES;